packages:
  - apps/*

allowBuilds:
  '@nestjs/core': true
  '@swc/core': true
  esbuild: true
  lightningcss: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@tanstack/react-start-rsc@0.1.32'
  - '@tanstack/react-start@1.168.33'
  - '@vitejs/plugin-react@6.0.5'
