packages:
  - apps/*
  - packages/*

allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@swc/core': true
  better-sqlite3: true
  esbuild: true
  lightningcss: true
  prisma: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@tanstack/react-start-rsc@0.1.32'
  - '@tanstack/react-start@1.168.33'
  - '@vitejs/plugin-react@6.0.5'
